require("config")
require("resources")
require("util")
-- objects
require("map")
require("phone")
require("player")
require("enemy")
require("knife")
require("fork")
require("weapon")
require("tomato")
-- gamestates
require("opening")
require("mainmenu")
require("directions")
require("introduction")
require("stairs")
require("kitchen")
require("livingroom")
require("bedroom")
require("ending")
-- 3rd party libraries
require("AnAL")
require("slam")
require("TSerial")
